plugins:
  - rubocop-rails
  - rubocop-capybara

Style/FrozenStringLiteralComment:
  Enabled: false

Style/Documentation:
  Enabled: false

AllCops:
    NewCops: enable

Rails/SkipsModelValidations:
  Enabled: false

Metrics/ClassLength:
  Exclude:
    - "test/**/*"
